# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qKjg2jEA6VLV36FuRDz4FaOWccrRQa6H
"""

Alcon = {"Age":21, True:2.18}

print(Alcon[True])